# Generated by Django 4.2.3 on 2023-07-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post uchun sarlavha kiriting', max_length=5000, verbose_name='Post nomi')),
                ('image', models.ImageField(help_text='Post uchun rasm kiriting', upload_to='post-images', verbose_name='Post rasmi')),
            ],
        ),
    ]
